graph.o: arc.h node.h graph.h graph.cpp
	$(CXX) $(CPPFLAGS) -c -o graph.o

track.o: junction.h track.h track.cpp
	$(CXX) $(CPPFLAGS) -c -o track.o
	
train.o: train.h train.cpp
	$(CXX) $(CPPFLAGS) -c -o train.o